In [1]:
import tensorflow as tf


In [6]:
arr = [[[[1.0],[1.0],[1.0],[1.0],[1.0],[1.0]],
[[1.0],[1.0],[1.0],[1.0],[1.0],[1.0]],
[[1.0],[1.0],[1.0],[1.0],[1.0],[1.0]],
[[1.0],[1.0],[1.0],[1.0],[1.0],[1.0]],
[[1.0],[1.0],[1.0],[1.0],[1.0],[1.0]],
[[1.0],[1.0],[1.0],[1.0],[1.0],[1.0]]]]
inputs = arr
arr2 = [
    [[[1.0]],[[1.0]],[[1.0]],[[1.0]],[[1.0]]],
    [[[1.0]],[[1.0]],[[1.0]],[[1.0]],[[1.0]]],
    [[[1.0]],[[1.0]],[[1.0]],[[1.0]],[[1.0]]],
    [[[1.0]],[[1.0]],[[1.0]],[[1.0]],[[1.0]]],
    [[[1.0]],[[1.0]],[[1.0]],[[1.0]],[[1.0]]]
]
arr3 = [
    [[[1.0]],[[1.0]],[[1.0]]],
    [[[1.0]],[[1.0]],[[1.0]]],
    [[[1.0]],[[1.0]],[[1.0]]]
]
filters = arr2
outputs = tf.nn.conv2d(inputs,filter=filters,strides=[1,1,1,1],padding="SAME")

In [7]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(outputs.eval())
    print(outputs.shape)

[[[[ 9.]
   [12.]
   [15.]
   [15.]
   [12.]
   [ 9.]]

  [[12.]
   [16.]
   [20.]
   [20.]
   [16.]
   [12.]]

  [[15.]
   [20.]
   [25.]
   [25.]
   [20.]
   [15.]]

  [[15.]
   [20.]
   [25.]
   [25.]
   [20.]
   [15.]]

  [[12.]
   [16.]
   [20.]
   [20.]
   [16.]
   [12.]]

  [[ 9.]
   [12.]
   [15.]
   [15.]
   [12.]
   [ 9.]]]]
(1, 6, 6, 1)


In [8]:
filters2 = arr3
outputs2 = tf.nn.conv2d_transpose(inputs,filter=filters2,strides=[1,2,2,1],output_shape=[1,12,12,1],padding="SAME")

In [9]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    res = outputs2.eval()
    print(outputs2.shape)

(1, 12, 12, 1)


In [10]:
for i in res[0]:
    for j in i:
        print(j, end=" ")
    print()


[1.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] 
[1.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] 
[2.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] 
[1.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] 
[2.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] 
[1.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] 
[2.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] 
[1.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] 
[2.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] 
[1.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] 
[2.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] [4.] [2.] 
[1.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] [2.] [1.] 


In [13]:
inputs = tf.Variable(tf.random_normal(shape=[1,224,224,3]))
filters = tf.random_normal(shape=[4,4,3,32])
outputs = tf.nn.conv2d(input=inputs, filter=filters, strides=[1,2,2,1], padding="SAME")

In [14]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(outputs.shape)

(1, 112, 112, 32)
