In [1]:
import tensorflow as tf

In [12]:
x = tf.random_normal(shape=[1000])
with tf.Session() as sess:
    print(tf.reduce_mean(x).eval())

0.039105546


In [38]:
x = tf.random_normal(shape=[1,20])
logits = tf.layers.dense(inputs=x,units=10)
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(x.eval())
    print(logits.eval())

[[ 1.0615404  -1.1010092  -0.6201155  -0.13284545 -0.72726184 -0.74165
   0.39026952  0.42741868 -1.7638233  -1.5197575  -0.11296666  0.28181326
  -0.18206224 -1.2781969  -0.7760326   0.42673478  1.9641671  -1.0323434
  -0.5155932  -1.5554093 ]]
[[ 0.11998683 -0.5753474  -1.0477406   0.11418985  0.8303393   0.48975947
   0.14567429  1.528068    0.01314923 -1.705693  ]]


In [70]:
x = [
    [[1,1,1],[2,2,2],[3,3,3],[4,4,4]],
    [[2,2,2],[2,2,2],[3,3,3],[4,4,4]],
    [[3,3,3],[2,2,2],[3,3,3],[4,4,4]]
]
x = tf.constant(x)
flat = tf.reshape(x,[-1])
with tf.Session() as sess:
    print(flat.eval())

[1 1 1 2 2 2 3 3 3 4 4 4 2 2 2 2 2 2 3 3 3 4 4 4 3 3 3 2 2 2 3 3 3 4 4 4]


In [4]:
x = tf.random_normal(shape=[2,3,3])
cell = tf.contrib.rnn.BasicRNNCell(num_units=5,name="ss",reuse=True)
output,state= tf.nn.dynamic_rnn(cell,x,dtype=tf.float32)
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    sess.run([output])
    print(output.eval())
    #print(state.eval())

[[[-0.72385186 -0.15721282 -0.6690165   0.9466805   0.7351912 ]
  [ 0.0269391  -0.33638147  0.8433796  -0.9656465  -0.02059385]
  [-0.5875402  -0.2383822   0.13429902  0.39443013 -0.3442715 ]]

 [[-0.32181597  0.40183473  0.10974472  0.05467901 -0.30301556]
  [ 0.49757424 -0.34977448 -0.18670985  0.412724    0.56845194]
  [ 0.70501363 -0.7909456  -0.230274   -0.19858578  0.38688168]]]
