In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable(tf.random_normal([3]),name="x")
y = tf.Variable(tf.random_normal([3]),name="y")
z = tf.add(x,y,name="output")
saver = tf.train.Saver()
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    saver.save(sess,"saved/test1.ckpt")
    print(x.eval())
    print(y.eval())
    print(z.eval())

[-0.41386846 -0.41979307 -1.1623191 ]
[-0.76006144 -1.5420774  -0.11554498]
[-1.1739299 -1.9618704 -1.2778641]


In [7]:
with tf.Session() as sess:
    saver = tf.train.import_meta_graph("saved/test1.ckpt.meta")
    saver.restore(sess,"saved/test1.ckpt")
    graph = tf.get_default_graph()
    out = graph.get_tensor_by_name("output:0")
    print(graph.get_tensor_by_name("x:0").eval())
    print(graph.get_tensor_by_name("y:0").eval())
    print(out.eval())

INFO:tensorflow:Restoring parameters from saved/test1.ckpt
[-0.41386846 -0.41979307 -1.1623191 ]
[-0.76006144 -1.5420774  -0.11554498]
[-1.1739299 -1.9618704 -1.2778641]


In [17]:
with tf.Session() as sess:
    saver = tf.train.import_meta_graph("saved/test1.ckpt.meta")
    saver.restore(sess,"saved/test1.ckpt")
    graph = tf.get_default_graph()
    w = tf.constant(1.0)
    out = graph.get_tensor_by_name("output:0")
    newout = out+w
    print(newout.eval())

INFO:tensorflow:Restoring parameters from saved/test1.ckpt
[-0.1739299  -0.9618705  -0.27786404]


In [24]:
with tf.Session() as sess:
    saver = tf.train.import_meta_graph("saved/test1.ckpt.meta")
    saver.restore(sess,"saved/test1.ckpt")
    graph = tf.get_default_graph()
    x1 = graph.get_tensor_by_name("x:0")
    tf.assign(x1,[1.0,1.0,1.0]).eval()
    y1 = graph.get_tensor_by_name("y:0")
    tf.assign(y1,[1.0,1.0,1.0]).eval()
    out = graph.get_tensor_by_name("output:0")
    print(out.eval())

INFO:tensorflow:Restoring parameters from saved/test1.ckpt
[2. 2. 2.]


In [16]:
from tensorflow.python.framework import graph_util
with tf.Session() as sess:
    saver = tf.train.import_meta_graph("saved/test1.ckpt.meta")
    saver.restore(sess,"saved/test1.ckpt")
    graph = tf.get_default_graph()
    print(graph.get_tensor_by_name("x:0"))
    graph_def = graph.as_graph_def()
#     print(graph_def)
    output_node_names = ["output"]
    output_graph_def = graph_util.convert_variables_to_constants(sess=sess,input_graph_def=graph_def,output_node_names=output_node_names)
#     print(output_graph_def)
#     print(output_graph_def.SerializeToString())

INFO:tensorflow:Restoring parameters from saved/test1.ckpt
Tensor("x:0", shape=(3,), dtype=float32_ref)
INFO:tensorflow:Froze 2 variables.
INFO:tensorflow:Converted 2 variables to const ops.
b'\n:\n\x01x\x12\x05Const*!\n\x05value\x12\x18B\x16\x08\x01\x12\x04\x12\x02\x08\x03"\x0c\x91\xe6\xd3\xbe\x1e\xef\xd6\xbe\xdf\xc6\x94\xbf*\x0b\n\x05dtype\x12\x020\x01\n4\n\x06x/read\x12\x08Identity\x1a\x01x*\x07\n\x01T\x12\x020\x01*\x14\n\x06_class\x12\n\n\x08\x12\x06loc:@x\n:\n\x01y\x12\x05Const*!\n\x05value\x12\x18B\x16\x08\x01\x12\x04\x12\x02\x08\x03"\x0cc\x93B\xbf\xcbb\xc5\xbf\xd9\xa2\xec\xbd*\x0b\n\x05dtype\x12\x020\x01\n4\n\x06y/read\x12\x08Identity\x1a\x01y*\x07\n\x01T\x12\x020\x01*\x14\n\x06_class\x12\n\n\x08\x12\x06loc:@y\n&\n\x06output\x12\x03Add\x1a\x06x/read\x1a\x06y/read*\x07\n\x01T\x12\x020\x01\x12\x00'


In [4]:
with tf.Session() as sess:
    saver = tf.train.import_meta_graph("saved/test1.ckpt.meta")
    graph = tf.get_default_graph()
    print(graph.get_tensor_by_name("x:0"))

Tensor("x:0", shape=(3,), dtype=float32_ref)
